package frc.robot.subsystems;

import static edu.wpi.first.units.Units.*;

import com.ctre.phoenix6.SignalLogger;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;
import com.pathplanner.lib.auto.AutoBuilder;
import com.pathplanner.lib.config.PIDConstants;
import com.pathplanner.lib.config.RobotConfig;
import com.pathplanner.lib.controllers.PPHolonomicDriveController;
import edu.wpi.first.math.MathUtil;
import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.networktables.NetworkTableInstance;
import edu.wpi.first.networktables.StructPublisher;
import edu.wpi.first.wpilibj.DataLogManager;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;
import frc.robot.Constants;
import frc.robot.generated.TunerConstants.TunerSwerveDrivetrain;
import java.util.Optional;
import java.util.function.Supplier;

/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements Subsystem so it can easily
 * be used in command-based projects.
 *
 * <p>Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class CommandSwerveDrivetrain extends TunerSwerveDrivetrain implements Subsystem {

  private static final double kSimLoopPeriod = 0.004;
  private Notifier m_simNotifier = null;
  private double m_lastSimTime;

  private final SwerveRequest.ApplyRobotSpeeds m_pathApplyRobotSpeeds =
      new SwerveRequest.ApplyRobotSpeeds();

  private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
  private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
  private boolean m_hasAppliedOperatorPerspective = false;
  private Alliance m_lastAlliance = null;

  private final SwerveRequest.SysIdSwerveTranslation m_translationCharacterization =
      new SwerveRequest.SysIdSwerveTranslation();
  private final SwerveRequest.SysIdSwerveSteerGains m_steerCharacterization =
      new SwerveRequest.SysIdSwerveSteerGains();
  private final SwerveRequest.SysIdSwerveRotation m_rotationCharacterization =
      new SwerveRequest.SysIdSwerveRotation();

  private final VisionSubsystem m_visionSubsystem = new VisionSubsystem();

  /* === Field visualization === */
  private final StructPublisher<Pose2d> m_posePublisher =
      NetworkTableInstance.getDefault().getStructTopic("RobotPose", Pose2d.struct).publish();

  private final SysIdRoutine m_sysIdRoutineTranslation =
      new SysIdRoutine(
          new SysIdRoutine.Config(
              null,
              Volts.of(4),
              null,
              state -> SignalLogger.writeString("SysIdTranslation_State", state.toString())),
          new SysIdRoutine.Mechanism(
              output -> setControl(m_translationCharacterization.withVolts(output)), null, this));

  private final SysIdRoutine m_sysIdRoutineSteer =
      new SysIdRoutine(
          new SysIdRoutine.Config(
              null,
              Volts.of(7),
              null,
              state -> SignalLogger.writeString("SysIdSteer_State", state.toString())),
          new SysIdRoutine.Mechanism(
              volts -> setControl(m_steerCharacterization.withVolts(volts)), null, this));

  private final SysIdRoutine m_sysIdRoutineRotation =
      new SysIdRoutine(
          new SysIdRoutine.Config(
              Volts.of(Math.PI / 6).per(Second),
              Volts.of(Math.PI),
              null,
              state -> SignalLogger.writeString("SysIdRotation_State", state.toString())),
          new SysIdRoutine.Mechanism(
              output -> {
                setControl(m_rotationCharacterization.withRotationalRate(output.in(Volts)));
                SignalLogger.writeDouble("Rotational_Rate", output.in(Volts));
              },
              null,
              this));

  private SysIdRoutine m_sysIdRoutineToApply = m_sysIdRoutineTranslation;

  public CommandSwerveDrivetrain(
      SwerveDrivetrainConstants drivetrainConstants, SwerveModuleConstants<?, ?, ?>... modules) {
    super(drivetrainConstants, modules);
    configureShared();
    configureAutoBuilder();
  }

  public CommandSwerveDrivetrain(
      SwerveDrivetrainConstants drivetrainConstants,
      double odometryUpdateFrequency,
      SwerveModuleConstants<?, ?, ?>... modules) {
    super(drivetrainConstants, odometryUpdateFrequency, modules);
    configureShared();
    configureAutoBuilder();
  }

  public CommandSwerveDrivetrain(
      SwerveDrivetrainConstants drivetrainConstants,
      double odometryUpdateFrequency,
      Matrix<N3, N1> odometryStandardDeviation,
      Matrix<N3, N1> visionStandardDeviation,
      SwerveModuleConstants<?, ?, ?>... modules) {
    super(
        drivetrainConstants,
        odometryUpdateFrequency,
        odometryStandardDeviation,
        visionStandardDeviation,
        modules);
    configureShared();
    configureAutoBuilder();
  }

  private void configureShared() {
    if (Utils.isSimulation()) startSimThread();
  }

  public Command applyRequest(Supplier<SwerveRequest> request) {
    return run(() -> setControl(request.get()));
  }

  public Command sysIdQuasistatic(SysIdRoutine.Direction direction) {
    return m_sysIdRoutineToApply.quasistatic(direction);
  }

  public Command sysIdDynamic(SysIdRoutine.Direction direction) {
    return m_sysIdRoutineToApply.dynamic(direction);
  }

  private void configureAutoBuilder() {
    // SmartDashboard.putData("SwerveField", m_field2d);

    try {
      var config = RobotConfig.fromGUISettings();
      AutoBuilder.configure(
          () -> getState().Pose, // Supplier of current robot pose
          this::resetPose, // Consumer for seeding pose against auto
          () -> getState().Speeds, // Supplier of current robot speeds
          // Consumer of ChassisSpeeds and feedforwards to drive the robot
          (speeds, feedforwards) ->
              setControl(
                  m_pathApplyRobotSpeeds
                      .withSpeeds(speeds)
                      .withWheelForceFeedforwardsX(feedforwards.robotRelativeForcesXNewtons())
                      .withWheelForceFeedforwardsY(feedforwards.robotRelativeForcesYNewtons())),
          new PPHolonomicDriveController(
              // PID constants for translation
              new PIDConstants(13.734, 0, 0.22443),
              // PID constants for rotation
              new PIDConstants(0.58204, 0, 0.0056021)),
          config,
          // Assume the path needs to be flipped for Red vs Blue, this is normally the case
          () -> DriverStation.getAlliance().orElse(Alliance.Blue) == Alliance.Red,
          this // Subsystem for requirements
          );
    } catch (Exception ex) {
      DriverStation.reportError(
          "Failed to load PathPlanner config and configure AutoBuilder", ex.getStackTrace());
    }
  }

  @Override
  public void periodic() {
    // Get current alliance
    var allianceOptional = DriverStation.getAlliance();

    // Reset perspective flag if alliance changed or robot is disabled
    if (allianceOptional.isPresent()) {
      Alliance currentAlliance = allianceOptional.get();
      if (m_lastAlliance != currentAlliance) {
        m_hasAppliedOperatorPerspective = false;
        m_lastAlliance = currentAlliance;
      }
    }

    // Apply operator perspective if not yet applied or robot is disabled
    if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
      allianceOptional.ifPresent(
          allianceColor -> {
            setOperatorPerspectiveForward(
                allianceColor == Alliance.Red
                    ? kRedAlliancePerspectiveRotation
                    : kBlueAlliancePerspectiveRotation);
            m_hasAppliedOperatorPerspective = true;
          });
    }

    Pose2d currentPose = getState().Pose;
    m_posePublisher.set(currentPose);

    if (Utils.isSimulation()) {
      m_visionSubsystem.setSimRobotPose(currentPose);
    }

    var speeds = getState().Speeds;
    double translationSpeed = Math.hypot(speeds.vxMetersPerSecond, speeds.vyMetersPerSecond);
    boolean tooFast =
        translationSpeed > Constants.Vision.kMaxVisionTranslationSpeed
            || Math.abs(speeds.omegaRadiansPerSecond) > Constants.Vision.kMaxVisionRotationSpeed;

    if (!tooFast) {
      m_visionSubsystem.getLatestRightVisionMeasurement().ifPresent(m -> tryFuseVision(m, "Right"));
      m_visionSubsystem
          .getLatestForwardVisionMeasurement()
          .ifPresent(m -> tryFuseVision(m, "Forward"));
      m_visionSubsystem
          .getLatestReverseVisionMeasurement()
          .ifPresent(m -> tryFuseVision(m, "Reverse"));
    }
  }

  /**
   * Cross-sensor sanity check before fusing a vision measurement. Rejects poses that jump too far
   * from odometry or whose heading disagrees with the gyro, both of which are symptoms of AprilTag
   * pose-flipping or a miscalibrated camera transform. Bypassed while disabled so the pose can snap
   * in during field setup.
   */
  private void tryFuseVision(VisionSubsystem.VisionMeasurement m, String cameraName) {
    if (DriverStation.isDisabled()) {
      addVisionMeasurement(m.pose(), m.timestampSeconds(), m.stdDevs());
      return;
    }

    // Sample odometry at the frame capture time for an apples-to-apples comparison.
    Pose2d odomAtVisionTime = samplePoseAt(m.timestampSeconds()).orElse(getState().Pose);

    double jumpMeters = odomAtVisionTime.getTranslation().getDistance(m.pose().getTranslation());
    if (jumpMeters > Constants.Vision.kMaxPoseJumpMeters) {
      DataLogManager.log(
          "Vision/"
              + cameraName
              + " rejected by drivetrain: pose_jump "
              + String.format("%.2f", jumpMeters)
              + "m");
      return;
    }

    double headingDiffRad =
        Math.abs(
            MathUtil.angleModulus(
                m.pose().getRotation().getRadians() - odomAtVisionTime.getRotation().getRadians()));
    if (headingDiffRad > Constants.Vision.kMaxHeadingDisagreementRad) {
      DataLogManager.log(
          "Vision/"
              + cameraName
              + " rejected by drivetrain: heading_disagree "
              + String.format("%.1f", Math.toDegrees(headingDiffRad))
              + "deg");
      return;
    }

    addVisionMeasurement(m.pose(), m.timestampSeconds(), m.stdDevs());
  }

  private void startSimThread() {
    m_lastSimTime = Utils.getCurrentTimeSeconds();
    m_simNotifier =
        new Notifier(
            () -> {
              double now = Utils.getCurrentTimeSeconds();
              double dt = now - m_lastSimTime;
              m_lastSimTime = now;
              updateSimState(dt, RobotController.getBatteryVoltage());
            });
    m_simNotifier.startPeriodic(kSimLoopPeriod);
  }

  @Override
  public void addVisionMeasurement(Pose2d pose, double timestamp) {
    super.addVisionMeasurement(pose, Utils.fpgaToCurrentTime(timestamp));
  }

  @Override
  public void addVisionMeasurement(Pose2d pose, double timestamp, Matrix<N3, N1> stdDevs) {
    super.addVisionMeasurement(pose, Utils.fpgaToCurrentTime(timestamp), stdDevs);
  }

  @Override
  public Optional<Pose2d> samplePoseAt(double timestamp) {
    return super.samplePoseAt(Utils.fpgaToCurrentTime(timestamp));
  }
}
